export const dom = {};

export function initDom() {
  Object.assign(dom, {
    status: document.getElementById("status"),
    openSettings: document.getElementById("openSettings"),
    settingsDialog: document.getElementById("settingsDialog"),
    closeSettings: document.getElementById("closeSettings"),
    serverUrlInput: document.getElementById("serverUrlInput"),
    usernameInput: document.getElementById("usernameInput"),
    passwordInput: document.getElementById("passwordInput"),
    apiKeyInput: document.getElementById("apiKeyInput"),
    userSelect: document.getElementById("userSelect"),
    userIdInput: document.getElementById("userIdInput"),
    lyricsToggle: document.getElementById("lyricsToggle"),
    rememberToggle: document.getElementById("rememberToggle"),
    loadUsersBtn: document.getElementById("loadUsersBtn"),
    connectBtn: document.getElementById("connectBtn"),
    resetBtn: document.getElementById("resetBtn"),
    themeToggle: document.getElementById("themeToggle"),
    coverflowTrack: document.getElementById("coverflowTrack"),
    coverflowEmpty: document.getElementById("coverflowEmpty"),
    coverflowEmptyIcon: document.getElementById("coverflowEmptyIcon"),
    coverflowEmptyTitle: document.getElementById("coverflowEmptyTitle"),
    coverflowEmptySub: document.getElementById("coverflowEmptySub"),
    coverflowSection: document.getElementById("coverflowSection"),
    albumMeta: document.getElementById("albumMeta"),
    albumLine: document.getElementById("albumLine"),
    albumCount: document.getElementById("albumCount"),
    lyricsPanel: document.getElementById("lyricsPanel"),
    lyricsPaneToggle: document.getElementById("lyricsPaneToggle"),
    lyricsStatus: document.getElementById("lyricsStatus"),
    lyricsViewport: document.getElementById("lyricsViewport"),
    lyricsTrack: document.getElementById("lyricsTrack"),
    playlistPanel: document.getElementById("playlistPanel"),
    playlistPaneToggle: document.getElementById("playlistPaneToggle"),
    playlistTitle: document.getElementById("playlistTitle"),
    playlistStatus: document.getElementById("playlistStatus"),
    playlistList: document.getElementById("playlistList"),
    playlistTracks: document.getElementById("playlistTracks"),
    playlistBack: document.getElementById("playlistBack"),
    nowCover: document.getElementById("nowCover"),
    nowTitle: document.getElementById("nowTitle"),
    nowSub: document.getElementById("nowSub"),
    audio: document.getElementById("audio"),
    typeahead: document.getElementById("typeahead"),
    cornerControls: document.getElementById("cornerControls"),
  });
}
