export const state = {
  serverUrl: "",
  apiKey: "",
  userId: "",
  albums: [],
  activeIndex: 0,
  albumTotal: 0,
  windowed: false,
  windowStartIndex: 0,
  windowOffset: 0,
  prefetchToken: 0,
  isPrefetchingAhead: false,
  isPrefetchingBehind: false,
  isLoadingAlbums: false,
  loadToken: 0,
  openAlbumId: null,
  trackFocusIndex: null,
  trackFocusAlbumId: null,
  typeaheadQuery: "",
  typeaheadTimer: null,
  typeaheadLookupTimer: null,
  typeaheadLookupToken: 0,
  typeaheadLookupQuery: "",
  jumpToken: 0,
  lyrics: {
    trackId: null,
    lines: [],
    mode: "none",
    activeIndex: -1,
    pendingLines: null,
  },
  lyricsToken: 0,
  lyricsLineEls: [],
  currentTrack: null,
  currentAlbum: null,
  lyricsOnline: true,
  tracksByAlbum: new Map(),
  nowPlaying: null,
  playlists: [],
  playlistTracksById: new Map(),
  playlistView: "list",
  activePlaylistId: null,
  playlistPlayback: null,
  playlistsLoading: false,
  playlistLoadToken: 0,
};

export const ALBUM_PAGE_LIMIT = 120;
export const TYPEAHEAD_LOOKUP_DELAY = 250;
